### ISSUE TITLE
Usage with S3

### ISSUE THREAD

**Issue by leftys** [rams3sh/botocache#1]
Hi! Tried this with s3 and got `Error encountered : cannot pickle '_io.BufferedReader' object Retrying the same call without cached context.` when trying to read an s3 object. So if anyone considered using botocache with s3, be warned it might not work out of the box.

**Comment by rams3sh** [comment]
Hey @leftys 

Thanks for raising the issue. Would you be able to share the sample code which gave the above error. I will try from my end and figure out the issue.

**Comment by leftys** [comment]
```python
from boto3.session import Session
from cachetools_ext.fs import FSLRUCache

from botocache.botocache import botocache_context

cache = FSLRUCache(ttl=900, path=".cache", maxsize=1000)

# action_regex_to_cache parameter consists list of regex to be matched against a given action for considering the call to be cached
with botocache_context(cache=cache,
                       action_regex_to_cache=["List.*", "Get.*", "Describe.*"]):
  cached_session = Session()
  s3 = cached_session.client('s3')
  bucket = ''
  key = ''
  data = s3.get_object(Bucket = bucket, Key = key)
  print(data)
```

Result:


```
Error encountered : cannot pickle '_io.BufferedReader' object. Retrying the same call without cached context.
{...}
```

**Comment by rams3sh** [comment]
Actually it seems like the issue exists with the `FSLRUCache` that you are using because of this line https://github.com/olirice/cachetools_ext/blob/4ca00faf7d0b4a7afd9bf0d303f945d53d47be17/cachetools_ext/fs.py#L81.

It uses pickle in the background to cache.  This is a known issue with pickling.  Since botocache is agnostic of cache used as backend as long as it honors `cachetools` , this does not seem to be a direct issue with botocache, but more on the cache used along with botocache.

However. really appreciate to have put here so that this acts as future reference for others. Thanks !! 

You may want to customise FSLRUCache to not use pickle and experiment on other alternate libraries which achieves this and then use it along with botocache.

**Comment by leftys** [comment]
I believe it's not a responsibility of cache backend to ensure serialization of complex objects, that should be done by botocache. 

I think this should be solved by some (de)serialization process that would recognize some problematic cases and convert the BufferedReader object to the actual bytes read and back when deserializing. I understand this might be out of scope for this library though.

**Comment by rams3sh** [comment]
Closing the issue since this is out of current scope of botocache.
